blank_issues_enabled: false
contact_links:
  - name: ğŸ“– æ–‡æ¡£
    url: https://amagi.ikenxuan.com
    about: æŸ¥çœ‹å®˜æ–¹æ–‡æ¡£
  - name: ğŸ’¬ è®¨è®º
    url: https://github.com/ikenxuan/amagi/discussions
    about: åœ¨ Discussions ä¸­æé—®æˆ–è®¨è®º
