name: Publish Any Commit
on: [push, pull_request]

permissions: {}

jobs:
  release:
    name: Release Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Publish
        run: pnpm dlx pkg-pr-new@0.0 publish --pnpm --compact --json output.json

      - name: Add to Summary
        run: |
          if [ -f output.json ]; then
            echo "## ðŸ“¦ Continuous Release" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            for row in $(cat output.json | jq -r '.packages[] | @base64'); do
              name=$(echo $row | base64 -d | jq -r '.name')
              url=$(echo $row | base64 -d | jq -r '.url')
              echo "**${name}**" >> $GITHUB_STEP_SUMMARY
              echo '```bash' >> $GITHUB_STEP_SUMMARY
              echo "pnpm add ${url}" >> $GITHUB_STEP_SUMMARY
              echo '```' >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
            done
          fi